[project]
name = "pkm"
version = "0.1.0"
description = "Package Manager For Python"
authors = [{ name = "bennyl" }]
license = "MIT License"
readme = "README.md"
requires-python = "~3.8"
dependencies = []

[build-system]
build-backend = "pkm.api.buildsys"
backend-path = ["."]