[project]
name = "new-docs"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python= ">=3.8, <4.0"
authors = [{name="bennyl"}]
dependencies = ["sphinx >=4.5.0, <5"]

[build-system]
requires=["pkm"]
build-backend = "pkm.api.buildsys"