[project]
name = "pkm-cli"
version = "0.1.0"
description = "Command line interface for PKM"
readme = "README.md"
requires-python = ">=3.8, <4.0"
authors = [{ name = "bennyl" }]
license.text = "MIT License"
dependencies = ["questionary *", "pkm *", "jinja2 *"]

[project.scripts]
pkm = "pkm_cli.pkm_cli:main"

[tool.pkm.project]
application=true

[build-system]
backend-path = "../pkm/src"
build-backend = "pkm.api.buildsys"