[[package]]
name = "backports.entry-points-selectable"
version = "1.1.1"
description = "Compatibility shim providing selectable entry points for older implementations"
optional = false
python-versions = ">=2.7"

[package.extras]
docs = [ "sphinx",  "jaraco.packaging (>=8.2)",  "rst.linker (>=1.9)"]
testing = [ "pytest",  "pytest-flake8",  "pytest-cov",  "pytest-black (>=0.3.7)",  "pytest-mypy",  "pytest-checkdocs (>=2.4)",  "pytest-enabler (>=1.0.1)"]

[[package]]
name = "colorama"
version = "0.4.4"
description = "Cross-platform colored terminal text."
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"

[[package]]
name = "commonmark"
version = "0.9.1"
description = "Python parser for the CommonMark Markdown spec"
optional = false
python-versions = "*"

[package.extras]
test = [ "flake8 (==3.7.8)",  "hypothesis (==3.55.3)"]

[[package]]
name = "distlib"
version = "0.3.4"
description = "Distribution utilities"
optional = false
python-versions = "*"

[[package]]
name = "filelock"
version = "3.4.0"
description = "A platform independent file lock."
optional = false
python-versions = ">=3.6"

[package.extras]
docs = [ "furo (>=2021.8.17b43)",  "sphinx (>=4.1)",  "sphinx-autodoc-typehints (>=1.12)"]
testing = [ "covdefaults (>=1.2.0)",  "coverage (>=4)",  "pytest (>=4)",  "pytest-cov",  "pytest-timeout (>=1.4.2)"]

[[package]]
name = "packaging"
version = "21.3"
description = "Core utilities for Python packages"
optional = false
python-versions = ">=3.6"
dependencies = {pyparsing = ">=2.0.2,<3.0.5 || >3.0.5"}

[[package]]
name = "pkginfo"
version = "1.8.2"
description = "Query metadatdata from sdists / bdists / installed packages."
optional = false
python-versions = "*"

[package.extras]
testing = [ "coverage",  "nose"]

[[package]]
name = "pkm"
version = "0.1.0"
description = "Package Manager For Python"
optional = false
python-versions = "^3.6"
dependencies = {typing-extensions = "^3.10.0.2"}
source = {type = "directory", url = "../../.."}
develop = true

[[package]]
name = "platformdirs"
version = "2.4.0"
description = "A small Python module for determining appropriate platform-specific dirs, e.g. a \"user data dir\"."
optional = false
python-versions = ">=3.6"

[package.extras]
docs = [ "Sphinx (>=4)",  "furo (>=2021.7.5b38)",  "proselint (>=0.10.2)",  "sphinx-autodoc-typehints (>=1.12)"]
test = [ "appdirs (==1.4.4)",  "pytest (>=6)",  "pytest-cov (>=2.7)",  "pytest-mock (>=3.6)"]

[[package]]
name = "pygments"
version = "2.10.0"
description = "Pygments is a syntax highlighting package written in Python."
optional = false
python-versions = ">=3.5"

[[package]]
name = "pyparsing"
version = "3.0.6"
description = "Python parsing module"
optional = false
python-versions = ">=3.6"

[package.extras]
diagrams = [ "jinja2",  "railroad-diagrams"]

[[package]]
name = "rich"
version = "10.15.2"
description = "Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal"
optional = false
python-versions = ">=3.6.2,<4.0.0"
dependencies = {colorama = ">=0.4.0,<0.5.0", commonmark = ">=0.9.0,<0.10.0", pygments = ">=2.6.0,<3.0.0"}

[package.extras]
jupyter = [ "ipywidgets (>=7.5.1,<8.0.0)"]

[[package]]
name = "six"
version = "1.16.0"
description = "Python 2 and 3 compatibility utilities"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*"

[[package]]
name = "typing-extensions"
version = "4.0.0"
description = "Backported and Experimental Type Hints for Python 3.6+"
optional = false
python-versions = ">=3.6"

[[package]]
name = "urllib3"
version = "1.26.7"
description = "HTTP library with thread-safe connection pooling, file post, and more."
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <4"

[package.extras]
brotli = [ "brotlipy (>=0.6.0)"]
secure = [ "pyOpenSSL (>=0.14)",  "cryptography (>=1.3.4)",  "idna (>=2.0.0)",  "certifi",  "ipaddress"]
socks = [ "PySocks (>=1.5.6,!=1.5.7,<2.0)"]

[[package]]
name = "virtualenv"
version = "20.10.0"
description = "Virtual Python Environment builder"
optional = false
python-versions = "!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,>=2.7"
dependencies = {"backports.entry-points-selectable" = ">=1.0.4", distlib = ">=0.3.1,<1", filelock = ">=3.2,<4", platformdirs = ">=2,<3", six = ">=1.9.0,<2"}

[package.extras]
docs = [ "proselint (>=0.10.2)",  "sphinx (>=3)",  "sphinx-argparse (>=0.2.5)",  "sphinx-rtd-theme (>=0.4.3)",  "towncrier (>=21.3)"]
testing = [ "coverage (>=4)",  "coverage-enable-subprocess (>=1)",  "flaky (>=3)",  "pytest (>=4)",  "pytest-env (>=0.6.2)",  "pytest-freezegun (>=0.4.1)",  "pytest-mock (>=2)",  "pytest-randomly (>=1)",  "pytest-timeout (>=1)",  "packaging (>=20.0)"]

[metadata]
lock-version = "1.1"
python-versions = "^3.8"
content-hash = "78412abb5d33a1df1642be7f3e2aa8b30c5a2986b1f5e6edbb63fc4c32b44cff"

[metadata.files]
pkm = []

[[metadata.files."backports.entry-points-selectable"]]
file = "backports.entry_points_selectable-1.1.1-py2.py3-none-any.whl"
hash = "sha256:7fceed9532a7aa2bd888654a7314f864a3c16a4e710b34a58cfc0f08114c663b"

[[metadata.files."backports.entry-points-selectable"]]
file = "backports.entry_points_selectable-1.1.1.tar.gz"
hash = "sha256:914b21a479fde881635f7af5adc7f6e38d6b274be32269070c53b698c60d5386"

[[metadata.files.colorama]]
file = "colorama-0.4.4-py2.py3-none-any.whl"
hash = "sha256:9f47eda37229f68eee03b24b9748937c7dc3868f906e8ba69fbcbdd3bc5dc3e2"

[[metadata.files.colorama]]
file = "colorama-0.4.4.tar.gz"
hash = "sha256:5941b2b48a20143d2267e95b1c2a7603ce057ee39fd88e7329b0c292aa16869b"

[[metadata.files.commonmark]]
file = "commonmark-0.9.1-py2.py3-none-any.whl"
hash = "sha256:da2f38c92590f83de410ba1a3cbceafbc74fee9def35f9251ba9a971d6d66fd9"

[[metadata.files.commonmark]]
file = "commonmark-0.9.1.tar.gz"
hash = "sha256:452f9dc859be7f06631ddcb328b6919c67984aca654e5fefb3914d54691aed60"

[[metadata.files.distlib]]
file = "distlib-0.3.4-py2.py3-none-any.whl"
hash = "sha256:6564fe0a8f51e734df6333d08b8b94d4ea8ee6b99b5ed50613f731fd4089f34b"

[[metadata.files.distlib]]
file = "distlib-0.3.4.zip"
hash = "sha256:e4b58818180336dc9c529bfb9a0b58728ffc09ad92027a3f30b7cd91e3458579"

[[metadata.files.filelock]]
file = "filelock-3.4.0-py3-none-any.whl"
hash = "sha256:2e139a228bcf56dd8b2274a65174d005c4a6b68540ee0bdbb92c76f43f29f7e8"

[[metadata.files.filelock]]
file = "filelock-3.4.0.tar.gz"
hash = "sha256:93d512b32a23baf4cac44ffd72ccf70732aeff7b8050fcaf6d3ec406d954baf4"

[[metadata.files.packaging]]
file = "packaging-21.3-py3-none-any.whl"
hash = "sha256:ef103e05f519cdc783ae24ea4e2e0f508a9c99b2d4969652eed6a2e1ea5bd522"

[[metadata.files.packaging]]
file = "packaging-21.3.tar.gz"
hash = "sha256:dd47c42927d89ab911e606518907cc2d3a1f38bbd026385970643f9c5b8ecfeb"

[[metadata.files.pkginfo]]
file = "pkginfo-1.8.2-py2.py3-none-any.whl"
hash = "sha256:c24c487c6a7f72c66e816ab1796b96ac6c3d14d49338293d2141664330b55ffc"

[[metadata.files.pkginfo]]
file = "pkginfo-1.8.2.tar.gz"
hash = "sha256:542e0d0b6750e2e21c20179803e40ab50598d8066d51097a0e382cba9eb02bff"

[[metadata.files.platformdirs]]
file = "platformdirs-2.4.0-py3-none-any.whl"
hash = "sha256:8868bbe3c3c80d42f20156f22e7131d2fb321f5bc86a2a345375c6481a67021d"

[[metadata.files.platformdirs]]
file = "platformdirs-2.4.0.tar.gz"
hash = "sha256:367a5e80b3d04d2428ffa76d33f124cf11e8fff2acdaa9b43d545f5c7d661ef2"

[[metadata.files.pygments]]
file = "Pygments-2.10.0-py3-none-any.whl"
hash = "sha256:b8e67fe6af78f492b3c4b3e2970c0624cbf08beb1e493b2c99b9fa1b67a20380"

[[metadata.files.pygments]]
file = "Pygments-2.10.0.tar.gz"
hash = "sha256:f398865f7eb6874156579fdf36bc840a03cab64d1cde9e93d68f46a425ec52c6"

[[metadata.files.pyparsing]]
file = "pyparsing-3.0.6-py3-none-any.whl"
hash = "sha256:04ff808a5b90911829c55c4e26f75fa5ca8a2f5f36aa3a51f68e27033341d3e4"

[[metadata.files.pyparsing]]
file = "pyparsing-3.0.6.tar.gz"
hash = "sha256:d9bdec0013ef1eb5a84ab39a3b3868911598afa494f5faa038647101504e2b81"

[[metadata.files.rich]]
file = "rich-10.15.2-py3-none-any.whl"
hash = "sha256:43b2c6ad51f46f6c94992aee546f1c177719f4e05aff8f5ea4d2efae3ebdac89"

[[metadata.files.rich]]
file = "rich-10.15.2.tar.gz"
hash = "sha256:1dded089b79dd042b3ab5cd63439a338e16652001f0c16e73acdcf4997ad772d"

[[metadata.files.six]]
file = "six-1.16.0-py2.py3-none-any.whl"
hash = "sha256:8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254"

[[metadata.files.six]]
file = "six-1.16.0.tar.gz"
hash = "sha256:1e61c37477a1626458e36f7b1d82aa5c9b094fa4802892072e49de9c60c4c926"

[[metadata.files.typing-extensions]]
file = "typing_extensions-4.0.0-py3-none-any.whl"
hash = "sha256:829704698b22e13ec9eaf959122315eabb370b0884400e9818334d8b677023d9"

[[metadata.files.typing-extensions]]
file = "typing_extensions-4.0.0.tar.gz"
hash = "sha256:2cdf80e4e04866a9b3689a51869016d36db0814d84b8d8a568d22781d45d27ed"

[[metadata.files.urllib3]]
file = "urllib3-1.26.7-py2.py3-none-any.whl"
hash = "sha256:c4fdf4019605b6e5423637e01bc9fe4daef873709a7973e195ceba0a62bbc844"

[[metadata.files.urllib3]]
file = "urllib3-1.26.7.tar.gz"
hash = "sha256:4987c65554f7a2dbf30c18fd48778ef124af6fab771a377103da0585e2336ece"

[[metadata.files.virtualenv]]
file = "virtualenv-20.10.0-py2.py3-none-any.whl"
hash = "sha256:4b02e52a624336eece99c96e3ab7111f469c24ba226a53ec474e8e787b365814"

[[metadata.files.virtualenv]]
file = "virtualenv-20.10.0.tar.gz"
hash = "sha256:576d05b46eace16a9c348085f7d0dc8ef28713a2cabaa1cf0aea41e8f12c9218"