[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "light-the-torch", version = "0.3.5"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "light-the-torch", version = "0.3.5"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "pip", version = "20.2.4"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "pip", version = "20.2.4"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "pkm-ltt-repository", version = "0.1.0"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "pkm-ltt-repository", version = "0.1.0"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "pkm", version = "0.4.22"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "pkm", version = "0.4.22"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "pkm", version = "0.4.40"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "pkm-torch-repository", version = "0.1.0"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "download-torch-pkm-repo", version = "0.1.0"}