[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "rich", version = "11.1.0"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "rich", version = "11.1.0"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "rich", version = "11.1.0"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "rich", version = "11.1.0"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "jinja2", version = "3.0.3"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "wcwidth", version = "0.2.5"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "wcwidth", version = "0.2.5"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "wcwidth", version = "0.2.5"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "wcwidth", version = "0.2.5"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "psutil", version = "5.9.0"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "setproctitle", version = "1.2.2"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "setproctitle", version = "1.2.2"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "setproctitle", version = "1.2.2"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "setproctitle", version = "1.2.2"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "questionary", version = "1.10.0"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "questionary", version = "1.10.0"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "questionary", version = "1.10.0"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "questionary", version = "1.10.0"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "distro", version = "1.6.0"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "commonmark", version = "0.9.1"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "commonmark", version = "0.9.1"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "commonmark", version = "0.9.1"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "commonmark", version = "0.9.1"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "shellingham", version = "1.4.0"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "pygments", version = "2.11.2"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "pkm-cli", version = "0.4.26"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "pkm-cli", version = "0.4.32"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "pkm-cli", version = "0.4.43"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "pkm-cli", version = "0.4.43"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "markupsafe", version = "2.0.1"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "pkm", version = "0.3.0"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "pkm", version = "0.4.29"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "pkm", version = "0.4.51"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "pkm", version = "0.4.51"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "colorama", version = "0.4.4"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "colorama", version = "0.4.4"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "colorama", version = "0.4.4"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "colorama", version = "0.4.4"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "prompt-toolkit", version = "3.0.24"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "prompt-toolkit", version = "3.0.24"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "prompt-toolkit", version = "3.0.24"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "prompt-toolkit", version = "3.0.24"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "pyperclip", version = "1.8.2"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "xonsh", version = "0.11.0"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "xonsh", version = "0.11.0"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "xonsh", version = "0.12.3"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "xonsh", version = "0.12.3"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "Jinja2", version = "3.0.3"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "Jinja2", version = "3.0.3"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "Jinja2", version = "3.0.3"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "Pygments", version = "2.11.2"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "Pygments", version = "2.11.2"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "Pygments", version = "2.11.2"}

[[lock]]
env_markers_hash = "07e4e684d036503e48585cacfd48fe13"
package = {name = "MarkupSafe", version = "2.1.1"}

[[lock]]
env_markers_hash = "6ba324ff4b889cb435ef2074beb74bb2"
package = {name = "MarkupSafe", version = "2.0.1"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "MarkupSafe", version = "2.0.1"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "cffi", version = "1.15.0"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "cryptography", version = "37.0.2"}

[[lock]]
env_markers_hash = "79ee86e4eb9e59db4283c32cb8125ecc"
package = {name = "pycparser", version = "2.21"}