[[package]]
name = "dataclasses"
version = "0.8"
description = "A backport of the dataclasses module for Python 3.6"
optional = false
python-versions = ">=3.6, <3.7"

[[package]]
name = "typing-extensions"
version = "4.0.0"
description = "Backported and Experimental Type Hints for Python 3.6+"
optional = false
python-versions = ">=3.6"

[metadata]
lock-version = "1.1"
python-versions = "^3.6"
content-hash = "e4c070d9a565fa7b743487a4ef261ec27fcaaf6299f6b2e4f3046aa6c37cc5a1"

[[metadata.files.dataclasses]]
file = "dataclasses-0.8-py3-none-any.whl"
hash = "sha256:0201d89fa866f68c8ebd9d08ee6ff50c0b255f8ec63a71c16fda7af82bb887bf"

[[metadata.files.dataclasses]]
file = "dataclasses-0.8.tar.gz"
hash = "sha256:8479067f342acf957dc82ec415d355ab5edb7e7646b90dc6e2fd1d96ad084c97"

[[metadata.files.typing-extensions]]
file = "typing_extensions-4.0.0-py3-none-any.whl"
hash = "sha256:829704698b22e13ec9eaf959122315eabb370b0884400e9818334d8b677023d9"

[[metadata.files.typing-extensions]]
file = "typing_extensions-4.0.0.tar.gz"
hash = "sha256:2cdf80e4e04866a9b3689a51869016d36db0814d84b8d8a568d22781d45d27ed"