[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "pkm-conda-repository", version = "0.1.0"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "pycosat", version = "0.6.3"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "idna", version = "3.3"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "requests", version = "2.27.1"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "charset-normalizer", version = "2.0.12"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "ruamel-yaml-clib", version = "0.2.6"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "urllib3", version = "1.26.8"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "conda", version = "4.3.16"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "certifi", version = "2021.10.8"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "pkm", version = "0.4.22"}

[[lock]]
env_markers_hash = "7cf0490079ffb7f85f91a0a2c6b1fdd5"
package = {name = "ruamel-yaml", version = "0.17.21"}